version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management plugin
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Custom RabbitMQ config file
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
      RABBITMQ_DEFAULT_VHOST: /

  app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    environment:
      RABBITMQ_URL: amqp://myuser:mypassword@rabbitmq:5672

networks:
  app-network:
    driver: bridge
